### PR TITLE
Updated purchase functionality to API version 1.2.1

### PR DESCRIPTION
**Pull request by Sutharsan**
- Added PurchaseDataTrait.
- Added PurchaseDate to museum objects (full + compact).
- Replaced PurchaseData in tour by new method.
- Test coverage.

### CODE REVIEW

**Comment by bartfeenstra** [comment]
Thanks!

`PaidDataTraitTest` looks like it contains too many properties and too extensive a constructor. `PaidDataTraitTestTraitImplementation::__construct()` also contains documentation for non-existent function arguments.

**Comment by bartfeenstra** [comment]
All tests pass locally. Coverage looks good too, except that there is no test for `FullTour` at all. We should add a basic test for that class and add missing coverage in a follow-up issue.

**Comment by Sutharsan** [comment]
Updated PaidDataTraitTest.php cleaning up ```PaidDataTraitTest``` and ```PaidDataTraitTestTraitImplementation::__construct()```.

**Comment by bartfeenstra** [comment]
Thanks!

**Pull request merged**
