### PR TITLE
Move ::getTitle() and ::getLanguageCode() to MtgObjectInterface

### PR DESCRIPTION
**Pull request by Sutharsan**
This makes ::getTitle() and ::getLanguageCode() available in FullMtgObjectInterface and FullMtgObjectBase too. This simplifies code that has to work with both full and compact MtgObjects.

### CODE REVIEW

**Comment by bartfeenstra** [comment]
Thanks! A few comments:
- BadMethodCallException should be InvalidArgumentException, I think.
- Why the abstract methods in MtgObjectBase? The abstract methods are already inherited from the interface.

**Comment by bartfeenstra** [comment]
Also, could you make sure these changes are tested? Re-using the test methods from CompactMtgObjectBaseTest is probably the easiest.

**Comment by Sutharsan** [comment]
I will not debate who added the BadMethodCallException, as I agree with your proposed solution. Other changes and tests included.

**Comment by bartfeenstra** [comment]
Thanks! I cherry-picked the correct commits and pushed them by hand.

**Comment by bartfeenstra** [comment]
With regards to the commits that were to be ignored: your fixes make a good point. I wonder if we can add a generic kind of validation to the RequestBase class.

**Comment by bartfeenstra** [comment]
I missed this while reviewing the PR: when a method returns $this, its return value is always documented using `@return $this` and not using the name of the class or interface (See PhpDoc and PSR-5 for this).

**Pull request closed without merging**
