### PR TITLE
Add support for Google+ and Instragram to Publisher

### PR DESCRIPTION
**Pull request by Sutharsan**
This is required to get Google+ and Instragram URLs of the Publisher.

### CODE REVIEW

**Comment by bartfeenstra** [comment]
Thanks for the PR. The code looks excellent. Locally the tests work fine, with minor typos in the URLS (http versus https) used in the newly added tests. If you can fix those, I'd be happy to merge in your changes.

**Comment by bartfeenstra** [comment]
I made some changes to the master branch, including some that should improve test results. You may have to rebase your local feature branch to benefit from these improvements.

**Comment by Sutharsan** [comment]
Code updated for failing tests. https -> http

**Comment by bartfeenstra** [comment]
http://docs.travis-ci.com/user/pull-requests/ explains why all integration tests fail on Travis.

**Comment by bartfeenstra** [comment]
Failed asserting that two strings are identical.
Expected :http://instagram.com/amsterdammuseum
Actual   :http//instagram.com/amsterdammuseum
 <Click to see difference>

 /opt/local/apache2/htdocs/code/triquanta/libizi/tests/DataType/PublisherContactInformationTest.php:109

**Comment by bartfeenstra** [comment]
Thanks!

**Pull request merged**
